#! /bin/bash

# Construct paths with $CIRCLE_WORKING_DIRECTORY
FULL_SOURCE_DOCS_PATH="${CIRCLE_WORKING_DIRECTORY}/${SOURCE_REPO_DIRECTORY_PARAM}/${SOURCE_DOCS_DIR}"
SOURCE_REPO_DIRECTORY="${CIRCLE_WORKING_DIRECTORY}/${SOURCE_REPO_DIRECTORY_PARAM}"
TARGET_REPO_DIRECTORY="${CIRCLE_WORKING_DIRECTORY}/${TARGET_REPO_DIRECTORY_PARAM}"

{
  # Set environment variables for subsequent steps
  echo "export FULL_SOURCE_DOCS_PATH=\"${FULL_SOURCE_DOCS_PATH}\""
  echo "export SOURCE_REPO_DIRECTORY=\"${SOURCE_REPO_DIRECTORY}\""
  echo "export TARGET_REPO_DIRECTORY=\"${TARGET_REPO_DIRECTORY}\""
} >> "$BASH_ENV"

# Log Environment Variables
echo "DESCRIPTION: ${DESCRIPTION}"
echo "FULL_SOURCE_DOCS_PATH: ${FULL_SOURCE_DOCS_PATH}"
echo "GIT_EMAIL: ${GIT_EMAIL}"
echo "GIT_USERNAME: ${GIT_USERNAME}"
echo "LABEL: ${LABEL}"
echo "PROJECT_NAME: ${PROJECT_NAME}"
echo "SOURCE_DOCS_DIR: ${SOURCE_DOCS_DIR}"
echo "SOURCE_REPO_DIRECTORY: ${SOURCE_REPO_DIRECTORY}"
echo "TARGET_REPO: ${TARGET_REPO}"
echo "TARGET_REPO_DIRECTORY: ${TARGET_REPO_DIRECTORY}"

echo "Environment variables set"
